### ISSUE TITLE
Avatar tiles not fully randomized

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#90] opened 2017-01-30 12:29 UTC
Currently two avatars are always displayed twice. The code needs to be double-checked and if that's not the issue look into twig caching posing a potential issue.

**Comment by MichaelKohler** [comment] 2017-01-30 15:30
Not for me, can you reproduce on different devices?

**Comment by freaktechnik** [comment] 2017-01-30 15:31
Seems to work from my office PC. However on Saturday both me and @annevk had this phenomenon.

**Comment by annevk** [comment] 2017-01-30 16:09
I'm no longer seeing it either.

**Comment by MichaelKohler** [comment] 2017-03-15 14:09
Closing since this can't be reproduced anymore.. feel free to reopen once you could reproduce it again.

**Closed as completed by MichaelKohler** 2017-03-15 14:09 UTC
Labels: Bug, P2
