### ISSUE TITLE
Replace "Get in touch"

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#86] opened 2016-10-07 12:51 UTC
Let's replace the link and icon of "Get in touch" with a link to https://discourse.mozilla-community.org/c/communities/switzerland . Not sure what we could use as icon though.

![screen shot 2016-10-07 at 14 47 49](https://cloud.githubusercontent.com/assets/330324/19190383/86aaeb76-8c9d-11e6-9c3e-05e7a963c7ad.png)

**Comment by freaktechnik** [comment] 2016-10-07 13:01
that's already done. (in theory)

**Comment by freaktechnik** [comment] 2016-10-07 13:01
duplicate of #77

**Closed as completed** 2016-10-07 13:02 UTC
Labels: Duplicate, Feature, Question, Needs work, P1

**Comment by MichaelKohler** [comment] 2016-10-07 13:04
eeeh, right.. sorry :(
